version: "3.8"
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - 3000:4173
    volumes:
      - frontend:/home/container
    environment:
      - VITE_API_KEY=

volumes:
  frontend:
